Eric dev
mraznick/emp-front-end pull request #4
Opened 2022-08-02 18:41 UTC by xericguzman

css, still styling forms but everything else works fine

2022-08-02 18:45 UTC, mraznick requested changes
Requesting changes just so you can pull down most recent front end code that includes sign out function/button

2022-08-03 03:11 UTC, xericguzman reviewed
updated pgs login and acct create forms and buttons

2022-08-03 12:53 UTC, mraznick approved these changes

2022-08-03 12:58 UTC, mraznick approved these changes

2022-08-03 12:58 UTC, merged